config/routes.rb
Rails.application.routes.draw do
    
  root 'pages#home'
  resources :services
  
end

app/models/service.rb
class Service < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 80 }
  validates :description, presence: true, length: { maximum: 80 }
  validates :price, presence: true
  validates :delivery_time, presence: false
  validates :revisions, presence: false
  validates  :requirements, presence: true, length: { maximum: 1200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  private
    def service_params
      params.require(:service).permit(:title, :description, :price, :requirements)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninerr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,600, Ubuntu+Mono:400', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="hero">
  <div class="container">
    <div class="row">
      <div class="hero-heading">
        Do you need help? <br/>
        Find it on Ninerr
        <p>Look. Find. Deal.</p>
      </div>
      <div class="row">
        <div class="col-md-offset-3 col-md-6">
          <div class="input-group input-group-lg">
            <input type="text" class="form-control" placeholder="Need help?..">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                Find Services
              </button>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container section">
  <h1>
    Newest Gigs
  </h1>
  <div class="row">
    <div class="col-md-3">
      <div class="gig-card">
        <%= image_tag 'blog.jpg' %>
        <h4>
          I will write 300 words blog
        </h4>
        <h3>
          $6
        </h3>
      </div>
    </div>

    <div class="col-md-3">
      <div class="gig-card">
        <%= image_tag 'piano.jpg' %>
        <h4>
          I will teach you piano
        </h4>
        <h3>
          $6
        </h3>
      </div>
    </div>

    <div class="col-md-3">
      <div class="gig-card">
        <%= image_tag 'clean.jpg' %>
        <h4>
          I will clean your house
        </h4>
        <h3>
          $6
        </h3>
      </div>
    </div>

    <div class="col-md-3">
      <div class="gig-card">
        <%= image_tag 'guitar.jpg' %>
        <h4>
          I will teach you guitar
        </h4>
        <h3>
          $6
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/edit.html.erb
<h1>Services#edit</h1>
<p>Find me in app/views/services/edit.html.erb</p>

app/views/services/index.html.erb
<h1>Services#index</h1>
<p>Find me in app/views/services/index.html.erb</p>

app/views/services/new.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h2>Create your gig </h2>
    </div>
    <div class="panel-body">
        <%= form_for @service do |f| %>
            <% if @service.errors.any? %>
              <div class="alert alert-info">
                <h3>
                  Fix the following <%= pluralize(@service.errors.count, "error") %> before continuing:
                </h3>
                <ul>
                  <% @service.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
              <label>Gig Title</label>
              <%= f.text_area :title, placeholder: "Ex: I will do something I am really good at",
                  rows: "2", class:"form-control" %>
            </div>

            <div class="form-group">
              <label>Description</label>
              <%= f.text_area :description,
                  rows: "5", class:"form-control" %>
            </div>

            <div class="form-group">
              <label>Pricing</label>
              <div class="select-control">
                <%= f.select :price, [["$6", "6"], ["$12", "12"], ["$18", "$18"], ["$24", "$24"]], class:"form-control" %>
              </div>
            </div>

            <div class="form-group">
              <label>Requirements</label>
              <%= f.text_area :requirements, rows: "5", class:"form-control" %>
            </div>

             <%= f.submit "Publish Gig", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="container">
	<h1><%= @service.title %></h1>
	<p><%= @service.description %></p>
</div>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Ninerr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Join</a></li>
        <li><a href="#">Sign In</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <%= link_to "Start Selling", new_service_path, class:"btn btn-default navbar-btn" %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>